spring.application.name=project1-spring

spring.datasource.url=jdbc:h2:mem:project1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=nishad
spring.datasource.password=0000

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# when you want to put run an sql insertertion query again again , runafter table creation
spring.jpa.defer-datasource-initialization=true 