spring.application.name=project1-spring

server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:project1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=nishad
spring.datasource.password=0000

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true